import React from 'react'
import Head from 'next/head'
import { ToastContainer } from 'react-toastify'
import { COMMON } from '@/_constants/common'
import { Roboto } from 'next/font/google'
import 'react-toastify/dist/ReactToastify.min.css'
import '@/_styles/globals.css'

const font = Roboto({ subsets: ['latin'], weight: ['400'] })

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <Head>
        <title>Task Admin</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <body className={font.className}>
        <main className='content'>{children}</main>
        <ToastContainer autoClose={COMMON.AUTO_CLOSE_TOAST} />
      </body>
    </html>
  )
}
